---
title: "Epitope paper figures"
author: "Christine Markwalter"
date: "3/16/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(ggpubr)
library(survival)
library(survminer)
library(ggfortify)
library(ggpmisc)
```


# Color scheme
```{r}
strat_colors = c("#87B4C0", "#CE5B3B")
```


# Figure data
csp cd4+
```{r}

CD4_hazard <- readRDS("figures/robj/CD4_hazardplot.RDS")

CD4_homolsurv <-  readRDS("figures/robj/CD4_homol_fig_cutoff60.RDS")

CD4_homolcoxme <- readRDS("figures/robj/CD4_coxme_fig.RDS")

CD4_randomdist <- readRDS("figures/robj/CD4_perm_data_time_dist.RDS")

CD4_homolvrandom <- readRDS("figures/robj/CD4_homolvrandom_survival.RDS")

cd4_randomsurv <- readRDS("figures/robj/CD4_random_strat_survival.RDS")

cd4_logrank <- readRDS("figures/robj/CD4_random_logrank_chisq_fig.RDS")

cd4_randomcoxme <- readRDS("figures/robj/CD4_random_coxme_fig.RDS")

cd4_cutoff60 <- readRDS("figures/robj/CD4_freq_compare_cutoff60.RDS")

cd4_prev <- readRDS("figures/robj/CD4_type_prevalence_risk_fig.RDS")

cd4_effect_meas <- readRDS("figures/robj/CD4_effect_mod.RDS")

cd4_moi <- readRDS("figures/robj/cd4_moi_plot.RDS")

cd4_sunburst <- readRDS("figures/robj/cd4_sunburst.RDS")

cd4_homolrandom_Asx <- readRDS("figures/robj/CD4_homolvrandom_survival_Asx.RDS")

cd4_homolrandom_Sx <- readRDS("figures/robj/CD4_homolvrandom_survival_Sx.RDS")

```

csp cd8+
```{r}

CD8_hazard <- readRDS("figures/robj/CD8_hazardplot.RDS")

CD8_homolsurv <-  readRDS("figures/robj/CD8_homol_fig_cutoff60.RDS")

CD8_homolcoxme <- readRDS("figures/robj/CD8_coxme_fig.RDS")

CD8_randomdist <- readRDS("figures/robj/CD8_perm_data_time_dist.RDS")

CD8_homolvrandom <- readRDS("figures/robj/CD8_homolvrandom_survival.RDS")

CD8_randomsurv <- readRDS("figures/robj/CD8_random_strat_survival.RDS")

CD8_logrank <- readRDS("figures/robj/CD8_random_logrank_chisq_fig.RDS")

CD8_randomcoxme <- readRDS("figures/robj/CD8_random_coxme_fig.RDS")

CD8_cutoff60 <- readRDS("figures/robj/CD8_freq_compare_cutoff60.RDS")

cd8_prev <- readRDS("figures/robj/CD8_type_prevalence_risk_fig.RDS")

cd8_effect_meas <- readRDS("figures/robj/CD8_effect_mod.RDS")

cd8_moi <- readRDS("figures/robj/cd8_moi_plot.RDS")

cd8_sunburst <- readRDS("figures/robj/cd8_sunburst.RDS")

cd8_homolrandom_Asx <- readRDS("figures/robj/CD8_homolvrandom_survival_Asx.RDS")

cd8_homolrandom_Sx <- readRDS("figures/robj/CD8_homolvrandom_survival_Sx.RDS")

```


combined
```{r}

Combined_hazard <- readRDS("figures/robj/Combined_hazardplot.RDS")

Combined_homolsurv <-  readRDS("figures/robj/Combined_homol_fig_cutoff60.RDS")

Combined_homolcoxme <- readRDS("figures/robj/Combined_coxme_fig.RDS")

Combined_randomdist <- readRDS("figures/robj/Combined_perm_data_time_dist.RDS")

Combined_homolvrandom <- readRDS("figures/robj/Combined_homolvrandom_survival.RDS")

Combined_randomsurv <- readRDS("figures/robj/Combined_random_strat_survival.RDS")

Combined_logrank <- readRDS("figures/robj/Combined_random_logrank_chisq_fig.RDS")

Combined_randomcoxme <- readRDS("figures/robj/Combined_random_coxme_fig.RDS")

Combined_cutoff60 <- readRDS("figures/robj/Combined_freq_compare_cutoff60.RDS")

Combined_prev <- readRDS("figures/robj/Combined_type_prevalence_risk_fig.RDS")

Combined_effect_meas <- readRDS("figures/robj/Combined_effect_mod.RDS")

Combined_moi <- readRDS("figures/robj/combined_moi_plot.RDS")

Combined_homolrandom_Asx <- readRDS("figures/robj/Combined_homolvrandom_survival_Asx.RDS")

Combined_homolrandom_Sx <- readRDS("figures/robj/Combined_homolvrandom_survival_Sx.RDS")

```


dv10
```{r}
DV10_homolsurv <-  readRDS("figures/robj/DV10_homol_fig_cutoff60.RDS")

DV10_homolcoxme <- readRDS("figures/robj/DV10_coxme_fig.RDS")

DV10_homolvrandom <- readRDS("figures/robj/DV10_homolvrandom_survival.RDS")

DV10_homolrandom_Asx <- readRDS("figures/robj/DV10_homolvrandom_survival_Asx.RDS")

DV10_homolrandom_Sx <- readRDS("figures/robj/DV10_homolvrandom_survival_Sx.RDS")

dv10_moi <- readRDS("figures/robj/dv10_moi_plot.RDS")

dv10_sunburst <- readRDS("figures/robj/dv10_sunburst.RDS")
```



ama-1
```{r}

AMA_hazard <- readRDS("figures/robj/AMA_hazardplot.RDS")

AMA_homolsurv <-  readRDS("figures/robj/AMA_homol_fig_cutoff60.RDS")

AMA_homolcoxme <- readRDS("figures/robj/AMA_coxme_fig.RDS")

AMA_randomdist <- readRDS("figures/robj/AMA_perm_data_time_dist.RDS")

AMA_homolvrandom <- readRDS("figures/robj/AMA_homolvrandom_survival.RDS")

AMA_randomsurv <- readRDS("figures/robj/AMA_random_strat_survival.RDS")

AMA_logrank <- readRDS("figures/robj/AMA_random_logrank_chisq_fig.RDS")

AMA_randomcoxme <- readRDS("figures/robj/AMA_random_coxme_fig.RDS")

AMA_cutoff60 <- readRDS("figures/robj/AMA_freq_compare_cutoff60.RDS")

AMA_moi <- readRDS("figures/robj/ama_moi_plot.RDS")

AMA_sunburst <- readRDS("figures/robj/ama_sunburst.RDS")

AMA_homolrandom_Asx <- readRDS("figures/robj/AMA_homolvrandom_survival_Asx.RDS")

AMA_homolrandom_Sx <- readRDS("figures/robj/AMA_homolvrandom_survival_Sx.RDS")

```


c1L AMA-1 epitope
```{r}
c1L_hazard <- readRDS("figures/robj/c1L_hazardplot.RDS")

c1L_homolsurv <-  readRDS("figures/robj/c1L_homol_fig_cutoff60.RDS")

c1L_homolcoxme <- readRDS("figures/robj/c1L_coxme_fig.RDS")

c1L_randomdist <- readRDS("figures/robj/c1L_perm_data_time_dist.RDS")

c1L_homolvrandom <- readRDS("figures/robj/c1L_homolvrandom_survival.RDS")

c1L_randomsurv <- readRDS("figures/robj/c1L_random_strat_survival.RDS")

c1L_logrank <- readRDS("figures/robj/c1L_random_logrank_chisq_fig.RDS")

c1L_randomcoxme <- readRDS("figures/robj/c1L_random_coxme_fig.RDS")

c1L_cutoff60 <- readRDS("figures/robj/c1L_freq_compare_cutoff60.RDS")

c1L_prev <- readRDS("figures/robj/c1L_type_prevalence_risk_fig.RDS")

c1L_effect_meas <- readRDS("figures/robj/c1L_effect_mod.RDS")

c1L_moi <- readRDS("figures/robj/c1L_moi_plot.RDS")

c1L_sunburst <- readRDS("figures/robj/c1L_sunburst.RDS")

c1L_homolrandom_Asx <- readRDS("figures/robj/c1L_homolvrandom_survival_Asx.RDS")

c1L_homolrandom_Sx <- readRDS("figures/robj/c1L_homolvrandom_survival_Sx.RDS")

```



# Epitope/haplotype diversity
```{r}

my.formula <- y ~ x+0

cd4_moi_alt <- ggplot(cd4_moi$data, aes(x = HType_moi, y = cd4_moi)) +
  geom_bin2d(binwidth = 1, breaks = seq(0.5,17.5,1)) +
  coord_cartesian(xlim = c(1,17), ylim = c(1,17)) +
  scale_x_continuous(n.breaks = 9) +
  scale_y_continuous(n.breaks = 9) +
  scale_fill_viridis_c(trans = "log", direction = -1, breaks = c(1,10,50,200), option = "mako") +
  geom_smooth(method = lm,color="black")+
  labs(title=paste0("CSP Th2R"))+
  theme_bw()+
  stat_poly_eq(formula = my.formula,
               aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
               parse = TRUE)+
  labs(x = "Haplotype MOI", y = "Epitope MOI", fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5))

cd8_moi_alt <- ggplot(cd8_moi$data, aes(x = HType_moi, y = cd8_moi)) +
  geom_bin2d(binwidth = 1, breaks = seq(0.5,17.5,1)) +
  coord_cartesian(xlim = c(1,17), ylim = c(1,17)) +
  scale_x_continuous(n.breaks = 9) +
  scale_y_continuous(n.breaks = 9) +
  scale_fill_viridis_c(trans = "log", direction = -1, breaks = c(1,10,50,200), option = "mako") +
  geom_smooth(method = lm,color="black")+
  labs(title=paste0("CSP Th3R"))+
  theme_bw()+
  stat_poly_eq(formula = my.formula,
               aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
               parse = TRUE)+
  labs(x = "Haplotype MOI", y = "Epitope MOI", fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5))


c1L_moi_alt <- ggplot(c1L_moi$data, aes(x = HType_moi, y = c1L_moi)) +
  geom_bin2d(binwidth = 1, breaks = seq(0.5,19.5,1)) +
  coord_cartesian(xlim = c(1,18.5), ylim = c(1,18.5)) +
  scale_x_continuous(n.breaks = 10) +
  scale_y_continuous(n.breaks = 10) +
  scale_fill_viridis_c(trans = "log", direction = -1, breaks = c(1,10,50,200), option = "mako") +
  geom_smooth(method = lm,color="black")+
  labs(title=paste0("AMA-1"))+
  theme_bw()+
  stat_poly_eq(formula = my.formula,
               aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
               parse = TRUE)+
  labs(x = "Haplotype MOI", y = "Epitope MOI", fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5))

dv10_moi_alt <- ggplot(dv10_moi$data, aes(x = HType_moi, y = dv10_moi)) +
  geom_bin2d(binwidth = 1, breaks = seq(0.5,19.5,1)) +
  coord_cartesian(xlim = c(1,18.5), ylim = c(1,18.5)) +
  scale_x_continuous(n.breaks = 10) +
  scale_y_continuous(n.breaks = 10) +
  scale_fill_viridis_c(trans = "log", direction = -1, breaks = c(1,10,50,200), option = "mako") +
  geom_smooth(method = lm,color="black")+
  labs(title=paste0("DV10"))+
  theme_bw()+
  stat_poly_eq(formula = my.formula,
               aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
               parse = TRUE)+
  labs(x = "Haplotype MOI", y = "Epitope MOI", fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5))


##changing color of lines on sunburst plot
cd4_sunburst$mapping <- aes(x = as.factor(level), y = value, fill = fct_reorder(fill, value, sum), alpha = as.factor(level), color = factor(ifelse(level == 0, "white", "grey50")))
cd8_sunburst$mapping <- aes(x = as.factor(level), y = value, fill = fct_reorder(fill, value, sum), alpha = as.factor(level), color = factor(ifelse(level == 0, "white", "grey50")))
c1L_sunburst$mapping <- aes(x = as.factor(level), y = value, fill = fct_reorder(fill, value, sum), alpha = as.factor(level), color = factor(ifelse(level == 0, "white", "grey50")))
dv10_sunburst$mapping <- aes(x = as.factor(level), y = value, fill = fct_reorder(fill, value, sum), alpha = as.factor(level), color = factor(ifelse(level == 0, "white", "grey50")))

cd4_sunburst$layers[[1]]$aes_params$colour <- NULL
cd8_sunburst$layers[[1]]$aes_params$colour <- NULL
c1L_sunburst$layers[[1]]$aes_params$colour <- NULL
dv10_sunburst$layers[[1]]$aes_params$colour <- NULL





###Changing epitope type label to be more legible

dv10_sunburst$layers[[3]]$data$label <- "Epitope\ntype"
cd4_sunburst$layers[[3]]$data$label <- "Epitope\ntype"
cd8_sunburst$layers[[3]]$data$label <- "Epitope\ntype"
c1L_sunburst$layers[[3]]$data$label <- "Epitope\ntype"


dv10_sunburst$layers[[3]]$data$x <- 0.9
cd4_sunburst$layers[[3]]$data$x <- 0.9
cd8_sunburst$layers[[3]]$data$x <- 0.9
c1L_sunburst$layers[[3]]$data$x <- 0.9


sunburst_plot_vertical <- ggarrange(dv10_sunburst +
                             scale_color_manual(guide = "none", values = c("grey5", "white")) +
                               #labs(title = "CSP DV10") +
                             scale_alpha_manual(values = c("0" = 0, "1" = 1, "2" = 0.5), guide = "none") +
                                          theme(plot.title = element_text(hjust = 0.5, face = "bold"), plot.margin = unit(c(0,0,0,0), "cm")),
                             cd4_sunburst +
                                          #labs(title = "CSP Th2R") +
                             scale_color_manual(guide = "none", values = c("grey5", "white")) +
                             scale_alpha_manual(values = c("0" = 0, "1" = 1, "2" = 0.5), guide = "none") +
                                          theme(plot.title = element_text(hjust = 0.5, face = "bold"), plot.margin = unit(c(0,0,0,0), "cm")),
            cd8_sunburst +
                                          #labs(title = "CSP Th3R") +
              scale_color_manual(guide = "none", values = c("grey5", "white")) +
                             scale_alpha_manual(values = c("0" = 0, "1" = 1, "2" = 0.5), guide = "none") +
                                          theme(plot.title = element_text(hjust = 0.5, face = "bold"), plot.margin = unit(c(0,0,0,0), "cm")),
            c1L_sunburst +
                                          #labs(title = "AMA-1 c1L") +
              scale_color_manual(guide = "none", values = c("grey5", "white")) +
                             scale_alpha_manual(values = c("0" = 0, "1" = 1, "2" = 0.5), guide = "none") +
                                          theme(plot.title = element_text(hjust = 0.5, face = "bold"), plot.margin = unit(c(0,0,0,0), "cm")),
            ncol = 1,
            heights = c(1,1,1,1),
            labels = c("CSP DV10", "CSP Th2R", "CSP Th3R", "AMA-1 c1L"),
            label.x = -0.05,
            label.y = 0.5)



moi_plot_vertical <- ggarrange(NULL,
                      dv10_moi_alt +
              labs(title = NULL)+
                theme(plot.margin = unit(c(0,0,0,0), "cm")),
              NULL,
                      cd4_moi_alt +
              labs(title = NULL)+
                theme(plot.margin = unit(c(0,0,0,0), "cm")),
              NULL,
            cd8_moi_alt +
              labs( title = NULL)+
                theme(plot.margin = unit(c(0,0,0,0), "cm")),
            NULL,
            c1L_moi_alt +
              labs( title = NULL)+
                theme(plot.margin = unit(c(0,0,0,0), "cm")),
            NULL,
            ncol = 1,
            heights = c(0.05,1,0.2,1,0.2,1,0.2,1,0.1),
            align = "v",
            common.legend = TRUE,
            legend = "right")


moi_sunburst_vertical <- ggarrange(sunburst_plot_vertical,
                          moi_plot_vertical,
                          ncol = 2,
                          widths = c(6,4),
                          align = "h")

ggsave(plot = moi_sunburst_vertical, "figures/moi_sunburst_vertical.png", height = 15, width = 10)


```



# Reinfection with homologous epitopes (vs random)
```{r}

#All episodes

## Removing annotated rectangle that's in the way
CD4_homolvrandom$layers[[4]] <- NULL
CD8_homolvrandom$layers[[4]] <- NULL
c1L_homolvrandom$layers[[4]] <- NULL

homol_v_random <- ggarrange(CD4_homolvrandom +
                              labs(x = "", y = " \n \n \n \n \n \n ", title = "All episodes") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(plot.title = element_text(hjust = 0.5, size = 15, face = "bold"), axis.text.x = element_blank(), axis.ticks.x = element_blank()),
                            CD8_homolvrandom +
                              labs(y = " \n \n \n \n \n \nMedian probability of survival without reinfection", x = "") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_blank(), axis.ticks.x = element_blank()),
                            c1L_homolvrandom +
                              labs(x = "", y = " \n \n \n \n \n \n ") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(plot.title = element_text(hjust = 0.5)),
                            NULL,
                            common.legend = TRUE,
                            legend = "none",
                            ncol = 1,
                            heights = c(1.1,1,1,0.13),
                            labels = c("CSP Th2R", "CSP Th3R", "AMA-1 c1L"),
                            label.x = -0.09,
                            label.y = 0.6)

homol_v_random


#Asx

## Removing annotated rectangle that's in the way
cd4_homolrandom_Asx$layers[[4]] <- NULL
cd8_homolrandom_Asx$layers[[4]] <- NULL
c1L_homolrandom_Asx$layers[[4]] <- NULL

homol_v_random_Asx <- ggarrange(cd4_homolrandom_Asx +
                              labs(x = "", y = "", title = "Asymptomatic episodes") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(plot.title = element_text(hjust = 0.5, size = 15, face = "bold"), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
                            cd8_homolrandom_Asx +
                              labs(y = "", x = "") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
                            c1L_homolrandom_Asx +
                              labs(y = "") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()),
                            common.legend = TRUE,
                            legend = "bottom",
                            ncol = 1,
                            heights = c(1.1,1,1))

homol_v_random_Asx


#Sx

## Removing annotated rectangle that's in the way
cd4_homolrandom_Sx$layers[[4]] <- NULL
cd8_homolrandom_Sx$layers[[4]] <- NULL
c1L_homolrandom_Sx$layers[[4]] <- NULL

homol_v_random_Sx <- ggarrange(cd4_homolrandom_Sx +
                              labs(x = "", y = "", title = "Symptomatic episodes") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(plot.title = element_text(hjust = 0.5, size = 15, face = "bold"), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
                            cd8_homolrandom_Sx +
                              labs(y = "", x = "") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
                            c1L_homolrandom_Sx +
                              labs(x = "", y = "") +
                              geom_vline(xintercept = 60, linetype = "dotted") +
                              scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
                              theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()),
                            NULL,
                            common.legend = TRUE,
                            legend = "none",
                            ncol = 1,
                            heights = c(1.1,1,1,0.13))

homol_v_random_Sx


homol_random_All <- ggarrange(homol_v_random,
                              homol_v_random_Asx,
                              homol_v_random_Sx,
                              nrow = 1,
                              widths = c(1.2,1,1))

ggsave(plot = homol_random_All, "figures/homolrandom.png", width = 13, height = 10)



```


# Homologous reinfection
```{r}

homol_strat <- ggarrange(ggarrange(CD4_homolsurv$plot +
            geom_vline(xintercept = 60, linetype = "dotted") +
            labs(title = "CSP Th2R", x = "") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5), legend.position = "none"),
            NULL,
          CD4_homolsurv$table +
            theme(plot.title = element_text(size = 12)),
          heights = c(1,-0.02,0.2),
          ncol = 1),
          ggarrange(CD8_homolsurv$plot +
            geom_vline(xintercept = 60, linetype = "dotted") +
            labs(title = "CSP Th3R") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5), legend.position = "none", axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
            NULL,
          CD8_homolsurv$table +
            labs(title = "") +
            theme(plot.title = element_text(size = 12), axis.text.y = element_blank()),
          heights = c(1,-0.02,0.2),
          ncol = 1),
          ggarrange(c1L_homolsurv$plot +
            geom_vline(xintercept = 60, linetype = "dotted") +
            labs(title = "AMA-1 c1L", x = "") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5), legend.position = "none", axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
            NULL,
          c1L_homolsurv$table +
            labs(title = "") +
            theme(plot.title = element_text(size = 12), axis.text.y = element_blank()),
          heights = c(1,-0.02,0.2),
          ncol = 1),
          nrow = 1,
          widths = c(1.15,1,1))


homol_strat

ggsave(plot = homol_strat, "figures/homol_strat.png", width = 10, height = 5)


#changing y axis order of forest plots
CD4_homolcoxme$data$label <- factor(CD4_homolcoxme$data$label, levels = c("Age >15", "Age 5 - 15", "Male", "Type prevalence", "Mosquitoes > 50", 
"Symptomatic"))
CD8_homolcoxme$data$label <- factor(CD8_homolcoxme$data$label, levels = c("Age >15", "Age 5 - 15", "Male", "Type prevalence", "Mosquitoes > 50", 
"Symptomatic"))
c1L_homolcoxme$data$label <- factor(c1L_homolcoxme$data$label, levels = c("Age >15", "Age 5 - 15", "Male", "Type prevalence", "Mosquitoes > 50", 
"Symptomatic"))


homol_forestplots <- ggarrange(CD4_homolcoxme +
            labs(x="") +
              scale_x_continuous(trans = "log", breaks = c(0.5,1,2,4), limits = c(0.4,4)),
          NULL,
          CD8_homolcoxme +
              scale_x_continuous(trans = "log", breaks = c(0.5,1,2,4), limits = c(0.4,4))+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()),
          NULL,
          c1L_homolcoxme +
            labs(x="") +
              scale_x_continuous(trans = "log", breaks = c(0.5,1,2,4), limits = c(0.4,4)) +
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()),
          nrow = 1,
          widths = c(1.3, -0.022, 1, -0.022, 1))

homol_forestplots

homol_asxsx_fig <- ggarrange(ggarrange(NULL,
                    homol_strat,
                    nrow = 1,
                    widths = c(0.06,1)),
                    NULL,
          homol_forestplots,
          heights = c(3,0.2,1),
          labels = c("A", "", "B"),
          ncol = 1)


ggsave(plot = homol_asxsx_fig, "figures/homol_asxsx.png", width = 12, height = 6)



```


# Random reinfection
```{r}

random_strat <- ggarrange(cd4_randomsurv +
            geom_vline(xintercept = 60, linetype = "dotted") +
            labs(title = "CSP Th2R", x = "") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5)),
          CD8_randomsurv +
            geom_vline(xintercept = 60, linetype = "dotted") +
            labs(title = "CSP Th3R") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5), axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
          c1L_randomsurv +
            geom_vline(xintercept = 60, linetype = "dotted") +
            labs(title = "AMA-1 c1L", x = "") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5), axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()),
          nrow = 1,
          common.legend = TRUE,
          legend = "bottom",
          widths = c(1.15,1,1))


random_strat

ggsave(plot = random_strat, "figures/random_strat.png", width = 10, height = 4)

#changing y axis order of forest plots
cd4_randomcoxme$data$variable <- factor(cd4_randomcoxme$data$variable, levels = c("Symptomatic", "Mosquitoes > 50", "Type prevalence", "Male", 
"Age 5-15", "Age > 15"))
CD8_randomcoxme$data$variable <- factor(CD8_randomcoxme$data$variable, levels = c("Symptomatic", "Mosquitoes > 50", "Type prevalence", "Male", 
"Age 5-15", "Age > 15"))
c1L_randomcoxme$data$variable <- factor(c1L_randomcoxme$data$variable, levels = c("Symptomatic", "Mosquitoes > 50", "Type prevalence", "Male", 
"Age 5-15", "Age > 15"))


random_forestplots <- ggarrange(cd4_randomcoxme +
            labs(x="")+
              scale_x_continuous(trans = "log", breaks = c(0.5,1,2), limits = c(0.4,4)),
          NULL,
          CD8_randomcoxme +
              scale_x_continuous(trans = "log", breaks = c(0.5,1,2), limits = c(0.4,4))+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()),
          NULL,
          c1L_randomcoxme +
            labs(x="") +
              scale_x_continuous(trans = "log", breaks = c(0.5,1,2), limits = c(0.4,4))+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()),
          nrow = 1,
          widths = c(1.3, -0.022, 1, -0.022, 1))

random_forestplots

random_asxsx_fig <- ggarrange(ggarrange(NULL,
                    random_strat,
                    nrow = 1,
                    widths = c(0.06,1)),
                    NULL,
          random_forestplots,
          heights = c(3,0.2,1),
          labels = c("A", "", "B"),
          ncol = 1)


ggsave(plot = random_asxsx_fig, "figures/random_asxsx.png", width = 12, height = 6)



```


# Epitope frequency before and after 60 day cut-off
```{r}

epitope_freq <- ggarrange(cd4_cutoff60+
            labs(title = "CSP Th2R", x = "", y = "Epitope frequency with time to reinfection < 60 days") +
            theme(plot.title = element_text(hjust = 0.5)),
          CD8_cutoff60 +
            labs(title = "CSP Th3R", y = "", x = "Epitope frequency with time to reinfection 60+ days")+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.title = element_text(hjust = 0.5)),
          c1L_cutoff60+
            labs(title = "AMA-1 c1L", x = "", y = "")+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.title = element_text(hjust = 0.5)),
          nrow = 1,
          widths = c(1.06, 1, 1))

epitope_freq

ggsave(plot = epitope_freq, "figures/epitope_freq.png", width = 12, height = 4)

```


# Permuted distributions of time to reinfection
```{r}

perm_dists <- ggarrange(CD4_randomdist+
            labs(title = "CSP Th2R", x = "") +
            theme(plot.title = element_text(hjust = 0.5)),
          CD8_randomdist +
            labs(title = "CSP Th3R", y = "")+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.title = element_text(hjust = 0.5)),
          c1L_randomdist+
            labs(title = "AMA-1 c1L", x = "", y = "")+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.title = element_text(hjust = 0.5)),
          nrow = 1,
          widths = c(1.1, 1, 1))

ggsave(plot = perm_dists, "figures/perm_dists.png", width = 12, height = 5)



```


# Log-rank random v homologous
```{r}

log_rank <- ggarrange(cd4_logrank+
            labs(title = "CSP Th2R", x = "") +
            theme(plot.title = element_text(hjust = 0.5)),
          CD8_logrank +
            labs(title = "CSP Th3R", y = "")+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.title = element_text(hjust = 0.5)),
          c1L_logrank+
            labs(title = "AMA-1 c1L", x = "", y = "")+
            theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.title = element_text(hjust = 0.5)),
          nrow = 1,
          common.legend = TRUE,
          legend = "bottom",
          widths = c(1.1, 1, 1))

ggsave(plot = log_rank, "figures/log_rank.png", width = 12, height = 4)



```


# Prevalence effect
```{r}

prev <- ggarrange(cd4_prev+
                    scale_y_continuous(breaks=c(0,0.2,0.4,0.6,0.8,1),sec.axis = sec_axis(~.*300, name = "",breaks=c(50,100,150,200,250,300,350)))+
                    labs(x = "CSP Th2R Epitope Type", y = ""),
          cd8_prev +
            labs(x = "CSP Th3R Epitope Type"),
          c1L_prev +scale_y_continuous(breaks=c(0,0.2,0.4,0.6,0.8,1),sec.axis = sec_axis(~.*300, name = "",breaks=c(50,100,150,200,250,300,350)))+
            labs(x = "AMA-1 c1L Epitope Type", y = ""),
          ncol = 1,
          common.legend = TRUE,
          legend = "bottom",
          labels = c("A","B", "C"),
          label.x = -0.02)

emm <- ggarrange(cd4_effect_meas +
                   labs(x = "") +
                   scale_x_continuous(trans = "log", limits = c(0.07,1.5), breaks = c(0.1, 0.2, 0.5, 1)),
                 NULL,
                 cd8_effect_meas +
                   labs(x = "")+
                   scale_x_continuous(trans = "log", limits = c(0.07,1.5), breaks = c(0.1, 0.2, 0.5, 1)),
                 NULL,
                 c1L_effect_meas +
                   scale_x_continuous(trans = "log", limits = c(0.07,1.5), breaks = c(0.1, 0.2, 0.5, 1)),
                 ncol = 1,
                 heights = c(1,0.1,1,0.1,1))


prev_fig <- ggarrange(NULL,
                      prev,
                      NULL,
                      ggarrange(emm,
                                NULL,
                                ncol = 1,
                                heights = c(1,0.09)),
          nrow = 1,
          widths = c(0.03,3,0.05,1))

ggsave(plot = prev_fig, "figures/prev_fig.png", width = 10, height = 8)

```

# Combined Th2R/Th3R figure
```{r}

#moi fig
combined_moi_alt <- ggplot(Combined_moi$data, aes(x = HType_moi, y = combined_moi)) +
  geom_bin2d(binwidth = 1, breaks = seq(0.5,17.5,1)) +
  scale_x_continuous(n.breaks = 9) +
  scale_y_continuous(n.breaks = 9) +
  scale_fill_viridis_c(trans = "log", direction = -1, breaks = c(1,10,50,200), option = "mako") +
  geom_smooth(method = lm,color="black")+
  labs(title=paste0("CSP Th2R/Th3R"))+
  theme_bw()+
  stat_poly_eq(formula = my.formula,
               aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
               parse = TRUE)+
  labs(x = "Haplotype MOI", y = "Epitope MOI", fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5))


#random strat fig

Combined_randomcoxme$data$variable <- factor(Combined_randomcoxme$data$variable, levels = c("Symptomatic", "Mosquitoes > 50", "Type prevalence", "Male", 
"Age 5-15", "Age > 15"))

Combined_random_strat <- ggarrange(Combined_randomsurv +
            geom_vline(xintercept = 60, linetype = "dotted") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"),
            Combined_randomcoxme +
              scale_x_continuous(trans = "log", breaks = c(0.5,1,2), limits = c(0.4,4)),
            ncol = 1,
            heights = c(3,1))
            
            


#homol strat fig

Combined_homolcoxme$data$label <- factor(Combined_homolcoxme$data$label, levels = c("Age >15", "Age 5 - 15", "Male", "Type prevalence", "Mosquitoes > 50", 
"Symptomatic"))

Combined_homol_strat <- ggarrange(ggarrange(Combined_homolsurv$plot +
            geom_vline(xintercept = 60, linetype = "dotted") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            labs(title = "") +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5), legend.position = "none"),
            NULL,
          Combined_homolsurv$table +
            theme(plot.title = element_text(size = 12)),
          heights = c(1,-0.02,0.2),
          ncol = 1),
          Combined_homolcoxme +
            scale_x_continuous(trans = "log", breaks = c(0.5,1,2), limits = c(0.35,3)),
          ncol = 1,
          heights = c(3,1))


combined_combined <- ggarrange(combined_moi_alt +
            labs(title = "")+
              theme(legend.position = "bottom"),
          Combined_homolvrandom +
            labs(title = "") +
            geom_vline(xintercept = 60, linetype = "dotted") +
            scale_x_continuous(breaks = c(0,60,100,200,300,400)) +
            theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"),
          Combined_homol_strat+
            labs(title = ""),
          Combined_random_strat+
            labs(title = ""),
          ncol = 2,
          nrow = 2,
          heights = c(1,1.2),
          labels = c("A","B","C","D"),
          align = "hv")

ggsave(plot = combined_combined, "figures/combined_fig.png", width = 10, height = 10)


```

